apiVersion: v1
kind: Pod
metadata:
  name: no-resize 
spec:
  initContainers:
  - name: fs-owner-change
    image: busybox
    command:
    - chown
    - "root:1001"
    - "/app"
    volumeMounts:
    - mountPath: /app
      name: app-data 
  securityContext:
    fsGroup: 1001 
  containers:
  - command:
    - sleep
    - infinity 
    image: bitnami/kubectl:latest
    imagePullPolicy: Always
    name: kubectl 
    securityContext:
      runAsGroup: 1001
    volumeMounts:
      - mountPath: "/app"
        name: app-data 
  volumes:
    - name: app-data 
      persistentVolumeClaim:
        claimName: no-resize-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: no-resize-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
