---
apiVersion: v1
kind: Pod
metadata:
  name: resize
spec:
  initContainers:
  - name: fs-owner-change
    image: busybox
    command:
    - chown
    - "root:1001"
    - "/app"
    volumeMounts:
    - mountPath: /app
      name: app-data
  securityContext:
    fsGroup: 1001
  containers:
  - command:
    - sleep
    - infinity
    image: bitnami/kubectl:latest
    imagePullPolicy: Always
    name: kubectl
    securityContext:
      runAsGroup: 1001
    volumeMounts:
      - mountPath: "/app"
        name: app-data 
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: resize-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resize-claim
  annotations:
    resize.topolvm.io/storage_limit: 3Gi
    resize.topolvm.io/threshold: 10%
    resize.topolvm.io/increase: 1Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
